{{- if .Values.reloadToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puller.fullname" . }}-token
  labels:
    {{- include "puller.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.reloadToken | quote }}
{{- end -}}
