sonar.projectKey=KXIANGW_Online-Code-Test
sonar.organization=kxiangw
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src,worker/src,worker/puller/src
sonar.tests=backend/src/__tests__,frontend/src/__test__,worker/src/__tests__,worker/puller/src/__tests__,e2e
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/__tests__/**,**/__test__/**,**/*.test.ts,**/*.spec.ts
