# KEDA 配置
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-scaler
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: 1
  maxReplicaCount: 5 # 本地演示建議設小，避免資源崩潰
  triggers:
  - type: prometheus # 預設使用 Prometheus 指標觸發，具備高度通用性
    metadata:
      serverAddress: [http://prometheus-operated.monitoring.svc:9090](http://prometheus-operated.monitoring.svc:9090)
      metricName: queue_depth_average
      threshold: '100'
      query: sum(queue_waiting_messages{job="{{ .Release.Name }}"})