apiVersion: v2
name: common-worker
description: A Helm chart for OCT Worker Kubernetes deployment
type: application

# 這是這個 Helm Chart 自身的版本號（跟你的程式版本無關，通常固定即可）
version: 0.1.0

# 這是預設的應用程式版本
appVersion: "1.0.0"
