apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: oct-app
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: oct-app
      useAnnotations: true
  writeBackConfig:
    method: argocd
